services:
  web:
    build: .
    container_name: teach-me_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    env_file:
      - ./.env.local
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: mysql:8.3
    container_name: teach-me_mysql
    restart: always
    environment:
      MYSQL_DATABASE: teach-me_db
      MYSQL_USER: teach-me_user
      MYSQL_PASSWORD: teach-me_pwd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - teach-me_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: teach-me_phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    container_name: teach-me_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  teach-me_db_data:
